### ISSUE TITLE
Can't build d.ts errors. Npm release?

### ISSUE THREAD

**Issue by ofairfoul** [SitePen/dts-generator#4]
Hi, Thanks for putting this together it looks really cool. I tried building from master and easy-install branches but get 1000's of errors during the tsc step. It looks like bad d.ts references.
E.g.
```
typings/typescript/lib.dom.d.ts(11873,5): error TS2300: Duplicate identifier 'statusMessage'.
```
Do you have a pre-built version available in npm or are planning to release?

**Comment by jason0x43** [comment]
Check out the easy-install branch, remove any existing `node_modules` and `typings` directories, then run `npm install`.

**Comment by ofairfoul** [comment]
Thanks, I managed to get this working in the end. Despite all the type warnings it was still able to generate the js.

**Comment by jason0x43** [comment]
What OS and version of node are you using? There shouldn't be any type warnings.

**Comment by csnover** [comment]
I think I figured out what happened to the OP. `tsd rebundle` is, uh, overeager. It will attempt to take typings from `node_modules` and add *all* of them as references into the generated `typings/tsd.d.ts`. When TypeScript is installed in `node_modules` it then adds all of its d.ts files instead of just the ones specified in tsd.json. So, I guess we won’t be using that to automatically regenerate the tsd.d.ts.

**Comment by jason0x43** [comment]
Hmmm... You mean the project-local node_modules? That was where my typescript was, and inwas not getting warnings. I wondered if there might be something globally installed that was causing issues, though.
