### ISSUE TITLE
Ignore private members

### ISSUE THREAD

**Issue by francisco-verdugo** [SitePen/dts-generator#53]
I have noticed that private members defined on typescript files are also included in the resultant d.ts definition files. 
My question is: Considering these private members something that should not be used outside its containing class. Why are they included in the d.ts file? Should not be just ignored?
Does dts-generator plugin have any option to ignore these?

**Comment by kitsonk** [comment]
It is important to maintain them, because at run-time, there is no such thing as "private".  Therefore, if you are further developing code in TypeScript, there is no way to help TypeScript avoid name collisions on classes, unless TypeScript is aware of the private member.  So removing them would cause more problems that it would seem to fix.
