### ISSUE TITLE
Option to specify a folder of external d.ts definitions

### ISSUE THREAD

**Issue by ofairfoul** [SitePen/dts-generator#6]
The dts-bundle project allows you to specify a folder of external d.ts definition files to use for 3rd party dependencies without needing an explicit `/// <reference />` in your code.
This is really useful for large projects with lots of external libraries.

**Comment by csnover** [comment]
Have you looked at [tsd](https://github.com/DefinitelyTyped/tsd) to manage your ambient declarations? I’d like to improve the compiler so that it will just accept ambient libraries as arguments to the compiler (basically, similar to what you are mentioning in this ticket), but tsd does at least allow you to whittle down all your external libs to a single place so it simplifies the reference comment part for now.
