### ISSUE TITLE
Libraries examples?

### ISSUE THREAD

**Issue by thefabulousdev** [SitePen/dts-generator#66]
I'm curious to see how libraries handle the generation of declarations and if they tweak them further on their build process (which I am having to currently).

Are there any open source libraries using this tool?

**Comment by kitsonk** [comment]
On of the main reasons we built this package was because we couldn't effectively do this for [Dojo 2](https://dojotoolkit.org).

Examples where `dts-generator` is built into the distribution pipeline:

* [dojo/loader](/dojo/loader)
* [dojo/core](/dojo/core)
* [dojo/compose](/dojo/compose)
* [dojo/actions](/dojo/actions)
* [dojo/widgets](/dojo/widgets)
* [dojo/routing](/dojo/routing)
* [dojo/parser](/dojo/parser)
* [dojo/dom](/dojo/dom)

**Comment by thefabulousdev** [comment]
I see that the module exports are generated as paths such as 
```ts
import { Something } from 'src/something'
```
which does not work on node environments, is there any example of the library used on node projects?

**Comment by kitsonk** [comment]
> which does not work on node environments

How so?  What would you expect the module identifier to be for a given source code file?

**Comment by thefabulousdev** [comment]
Nevermind, my bad, I would have expected a single entry point for the generated hierarchy but I now realize it's better this way `jspm` wise
